### ISSUE TITLE
Colors are reversed on "Bash on Ubuntu on Windows"

### ISSUE THREAD

**Issue by davidalbertonogueira** [smiranda/microunit#2]
On "Bash on Ubuntu on Windows" passed tests are presented in red and failed ones in green.

![image](https://cloud.githubusercontent.com/assets/5329202/21664623/a17aa40e-d2df-11e6-85a7-7bf0bd8ea6ec.png)

**Comment by smiranda** [comment]
I'll install this platform on my machine to replicate the issue.
